### ISSUE TITLE
processes do not always get killed when npm-run-parallel exits

### ISSUE THREAD

**Issue by jcpst** [ianmcnally/npm-run-parallel#3]
In my `package.json` scripts object, I have something like:

``` js
"scripts": {
    "watch": "npm-watch",
    "serve": "json-server mock/db.json",
    "start": "npm-run-parallel watch serve",
}
```

I can run `npm run watch` and `npm run serve` with no issues. When I run the `npm start` task, and then `^c` out of it, I can't run it again, because the process is still alive and the `serve` script is blocking the port.

``` shell
$ ps -ef

joe       6323  6305 11 23:08 pts/0    00:00:00 node /home/joe/dev/js/cicada/node_modules/.bin/json-server mock/db.json
joe       6328     1  6 23:08 pts/0    00:00:00 node /home/joe/dev/js/cicada/node_modules/.bin/nodemon --watch src/main.sass --exec npm run build:css
```

Maybe there could be something in the `run.js` file that makes sure those processes are killed?

**Comment by ianmcnally** [comment]
Thanks for opening the issue. I'll look into it as soon as I can.

**Comment by ianmcnally** [comment]
Could you tell me what version your running? `npm-run-parallel --version`

**Comment by jcpst** [comment]
0.4.2

It appears to only happen when one of the `npm run` scripts that `npm-run-parallel` is calling exits with an error. Then those processes that `npm-run-parallel` called stay alive afterward. 

If I kill those processes, fix the error in my run script I'm calling, then I can use `npm-run-parallel` just as expected.

**Comment by ianmcnally** [comment]
got it, thanks!

**Comment by ianmcnally** [comment]
@jcpst adding a child process exiting when there's a signal interruption (ctrl-c) in b0967ca, and released it in 0.4.3. let me know how this works for you!

**Comment by jcpst** [comment]
Updated to 0.4.3 and still having the issue.

I can investigate this more later. So far it looks specific to run scripts that use `npm-watch`.

**Comment by ianmcnally** [comment]
Ok, let me know if I can help!
