### ISSUE TITLE
The '--color' argument leaks to lessc, browserify, and others

### ISSUE THREAD

**Issue by lordvlad** [ianmcnally/npm-run-parallel#6]
In my package.json I have the following tasks:

```
"scripts": {
  "build-css": "lessc src/styles.less > build/app.css",
  "build-js": "browserify src/index.js --debug | exorcist build/app.js.map > build/app.js",
  "build": "npm-run-parallel build-css build-js"
}
```

Now when I do `npm run build`, `lessc` complains that it cannot interpret the `--color` argument and browserify breaks similarly.

**Comment by itsMapleLeaf** [comment]
Should probably just get rid of the --color argument, honestly. Any CLI that supports it will have an argument for it that the user can add themselves, most of the time.

**Comment by ianmcnally** [comment]
Having colors, if supported, is a big requirement for me. PRs would be welcome and very appreciated. Thanks for taking the time to add to this!

**Comment by lordvlad** [comment]
Wouldn't it make more sense then to set the argument in the respective tasks? Like

```
"scripts": {
    "colorful": "colorful --color",
    "monochrome": "monochrome",
    "all": "npm-run-parallel monochrome colorful"
}
```

**Comment by ianmcnally** [comment]
That's one option but I want a solution where the user doesn't have to think about whether they want terminal colors or not. If a task prints in color it should be colored when running through this module.

**Comment by lordvlad** [comment]
But here I agree with @just-nobody. It should be the responsibility of THAT module. It shouldn't be `npm-run-parralel`s responsibility to tell every cli tool to use `--color`. Especially if there are cli tools that throw on unknown switches.

**Comment by itsMapleLeaf** [comment]
> That's one option but I want a solution where the user doesn't have to think about whether they want terminal colors or not. If a task prints in color it should be colored when running through this module.

And if the user never wants colors? Yes, those people exist.

**Comment by ianmcnally** [comment]
> And if the user never wants colors? Yes, those people exist.

I want the default experience, what ever that is.

**Comment by itsMapleLeaf** [comment]
The default experience is that without the --color argument. And some cli tools that don't support it will error if it's not a valid argument. Let's not forget some use `--color` and sometimes `--colors` and sometimes it's entirely different, there's no standard here.

This is a really stupid argument brought out of a really stupid change.

**Comment by ianmcnally** [comment]
@just-nobody it's incredibly inappropriate to start calling decisions, and by extension the people behind them, stupid. This is a free project that I've built to address my needs. And instead of working with me on a solution you plow onwards with shutdowns and insults. Take your negativity elsewhere.
