### ISSUE TITLE
automatically adding --color means all tasks fail (if the script does not support the argument) 

### ISSUE THREAD

**Issue by chee** [ianmcnally/npm-run-parallel#9]
i realise there is already a PR and an issue filed for this problem, but both of them are closed and locked.

## use case
i used `npm-run-parallel` for running `watchify`, `livereloadify` and `http-server`

## problem
the problem is, none of these commands support a `--color` argument

## expected behaviour
i'd want the commands to run as i defined them (there is no guarantee that passing `--color` will add colours, it could change the behaviour of the program or cause the program to exit badly)

## current behaviour
```error Command failed with exit code 1.```

**Comment by ianmcnally** [comment]
Thanks @chee. It's still an open issue. I closed the other one since it got heated there. PRs welcome, if you can. Otherwise, I'll add it to the backlog.

**Comment by lukeramsden** [comment]
Literally makes the tool *completely* useless.

**Comment by ianmcnally** [comment]
@lukeramsden fix it or leave. Your comment adds nothing to the conversation.
